### ISSUE TITLE
Enhancements for project and site

### ISSUE THREAD

**Issue by john-d-pelingo** [TimoSta/sprite#14]
First of all this project looks super amazing.

I have read the existing open issues but I hope that I am not writing a duplicate issue here.

- Issue template for Github. Pretty sure that issues will start popping out. Example  here https://github.com/facebook/react/blob/master/.github/ISSUE_TEMPLATE.md 
- I dunno how this is called but an ability to share code through the link like what babel REPL and typescript-play do:
  - https://babeljs.io/repl/#?babili=false&browsers=ie%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgziA2CmB00QHMAUByAZiE6CUQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-1%2Cenv&prettier=true&targets=&version=6.26.0&envVersion=1.6.2
  - https://typescript-play.js.org/#code/MYewdgziA2CmB00QHMAUByAZiE6CUQA
- Ability to import and export code

**Comment by TimoSta** [comment]
Hey John,
thanks a ton for the suggestions, they are great!!

1 and 3 are something I indeed haven't thought yet, and 2 is something I had in mind, but no chance to work on yet unfortunately.

To make it easier to assign and track the different points, I broke them out into #16, #17, and #18.

If you feel like helping out, feel free to submit a PR for any of the open issues! 🙂
